---
tags: []
layout: input_right
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- value: Hola
  checked: true
- value: Genial
  checked: false
- value: Todo bien?
  checked: false
